// <auto-generated />
namespace ThreeSisters.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddVirtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVirtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201504081905109_AddVirtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
